# Generated by Django 4.1.2 on 2024-07-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
